# 池化

## 1. 最大池化

![maxpool](https://d2l.ai/_images/pooling.svg)

### 2. 平均池化


### 3. padding和stride

padding和stride和卷积的定义一样

In [1]:
from d2l import torch as d2l
import torch
from torch import nn

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
print(X)
pool2d(X, (2, 2))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


tensor([[4., 5.],
        [7., 8.]])

In [4]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [5]:
X = d2l.reshape(torch.arange(16, dtype=torch.float32), (1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [6]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [7]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [8]:
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [9]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [10]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

## 总结

1. 池化可以被认为是一种不可学习的卷积操作（暴力但有效），max_pool, avg_pool都能将前层激活的特征较好的传递下去（激活函数都是单调非递减的，激活值越大特征越被需要）
2. 池化一般用于减少前层特征的个数(1D任务)，在2D/3D任务里，用于减少前层feature map的大小，且计算量非常小
3. max_pool具备一定的局部不变性（平移/旋转/缩放），可以提升模型的鲁棒性
4. 现在最新的证据表明，深度学习模型的泛化能力主要还是依赖于模型的深度(layer数)和广度(channel数)，所以在一些较新的网络里，会用stride >= 2的卷积代替Pooling操作，可以取得更好的效果，比如YOLO的darknet53，但是Pooling的计算量小，在小数据集/紧凑的网络里用处还是挺多的。